mon/BemaniPatcher

- jubeatprop.html
Locks the song select timer, in case event mode is not in use. Credits to Tzwcard.
> Add timer lock

- jubeatprop.html
> Fix missing commas

- sinobuz.html
> Add two Sinobuz hex edits

- sdvx4.html
> Fix IV safe banner patch

- sdvx4.html
Added Omega Dimension Matching by Default
> Added Omega Dimension Matching by Default

- sdvx4.html
Adds all songs safe, all unlocks, event mode boot & volume fix for 20180605
> Add 2018-06-05

- ballerz.html
I believe this should clear up all outstanding edits
> Added MANY hex edits

- ballerz.html
Added note to debug mode tooltip as it had some confusion
> updated Debug Mode tooltip

- ddra.html
> Two more DDR A hex edits (unlock options and force extra stage)

- ddra.html
Forgot a comma, forgot to test after adding tooltips >_<
> Forgot a comma .-.

- sdvx4.html
Hex edits for Sound Voltex 20180821
> SDVX 2018-08-21 hex edits

- ddra.html
> Fix extra stage hex edit, add disable credit hex edit

- ballerz.html
> updated a credit - misspelled name

- ddra.html
Added DarkBG filter to the list.
> One more A hex edit

- jubeatclan.html
Ash posted and granted permission to publish this edit from the jubeat Discord.
> Add online matching skip edit for jubeat clan 2018070901

- ddra.html
Everything I've found recently.
> New MDX edits

- popn25peace.html
> Add additional pop'n peace 20190423 edits

- museca2.html
Added a hexedit that allows the game to boot directly into Event Mode when Coin Mode is set to Free Play. Doesn't affect ability to toggle between Free Play and Event Mode from service menu.
> Added Auto Event Mode to museca2.html

- museca2.html
Added a hex that lets the game count up to the third song and then just loop from there. Kept the original 1st layer patch and leaving it up to Cammy on whether or not to get rid of it.
Please ignore the additional commits genius here forgot that pull existed
> Museca Infinite Final Layer

- museca2.html
Not sure if this should be combined with Infinite Final Layer. Thoughts?
> Added Start on Final Layer hex edit to museca2

- museca2.html
Sorry for not testing these edits enough before submitting, but I have thoroughly tested everything now. Turns out my original mod is required for all of Akubits' mods to work, otherwise we run into score saving issues. I fixed some offsets & merged our mods into one.
> Patch overhaul - thoroughly tested. 

- rootage.html
Replaced the hex with proper values. My first PR so let me know if anything is amiss.
> Fix "Free play text to LED ticker" Patch

- sdvx5.html
Credits to G3ORGE from /1cc/ for this one.
> SDVX 5: Add Unlock all Nemsys Crew

- sdvx5.html
> SDVX V: Add KFC-2019070900 patches

- sdvx5.html
We are truly going fast, aren't we? This didn't take too long.
> SDVX V: Add more patches and KFC-2019100800

- chuniamazon.html
Might not the best way to patch this.
Only tested with event mode, guest mode and card mode.
> Chuni: disable song select timer

- gitadoraexchain.html
Timer freeze works just like in past games, with a tiny tiny change to the offset.
> Gitadora Exchain: Timer Freeze added

- popn23eclale.html
added "remove timer" to Pop'n Eclale, patch has same logic as the one from Pop'n Peace
> Eclale: remove timer

- js/dllpatcher.js
Browsers are all weird........
> Fix drop event in Firefox

- jubeatfesto.html
I can't test the other hex edits from the other PR but these are tested and confirmed to work...
> add hex edits for 0727 and 0611 festo

- nostalgiaop2.html
Adds explicit support for the other op.2 release
> feat(op.2): Add support for 2019-10-02

- popn25peace.html
> 2019-06-25 offset ports

- popn25peace.html
Translating from ver.20190423. "Unlock all songs" looks different from old version, but it works. Not sure if "ALL" songs had been unlocked.
> feat(popn25): Add support for 2020-09-28

- chuniamazon.html
I merged Amazon+ patches into the Amazon page since im kinda lazy to create a new logo icon
> Add Chunithm Amazon Plus patches

- chunicrystal.html
Add Increase max credits to 254, Dummy LED, Free Play
> Add Increase max credits to 254, Dummy LED, Free Play

- chuniparadise.html
~~speechless for today's madness~~
> more patch for chuni 1.50

- chuniparadise.html
Add No Encryption, No TLS tooltip
> Add Increase max credits to 254 +a

- heroicverse.html
Breaks the path for the news cut-in sound effect. Some people find it annoying.
> Added Disable News Sound patch to IIDX27.

- sdvx6.html
I ran an autoformatter cus the formatting gave me a headache to look at. i can revert that if you want
> add Premium Time Length

- popn25peace.html
Reverts mon/BemaniPatcher#205
I've been informed this is actually keimei. Anyone who wants these patches, make a new patcher, add the image, add it to the index, do it properly.
> Revert "popn2021042600"

- bistrover.html
For news sound I'm taking a slightly different approach of using the dummy audio file.
> Port news sound patch and volume patch for Bistrover

- bistrover.html
> Bistrover: enable Lightning Model folder in LDJ

- jubeatfesto.html
and add "Unlock all songs" for 2020120801, 2020072701
> Separate 'jubeat.dll' and 'music_db.dll'

- taikonotatsujin.html
Ported these over to 08.18 long ago - surprised no one else has gotten round to popping these on Bemani Patcher so thought I might as well.
> Added patches for Nijiiro 08.18

- reflecbeat-reflesia.html
Add a few basic patches for reflesia with date codes 2018-12-11 and 2019-12-11.
> Add patches to reflec beat reflesia 2018 and 2019

- jubeatfesto.html
ported from 2020-07-27 patches
> add jubeat festo 2021-03-31 patches

- ddrx.html
Please let me know if there is anything that needs adjusting; I'm new to using GitHub.
> Add fix for 5-2002-0001 (200963000)

- bistrover.html
Skips most of the 'stage failed' animation.
https://streamable.com/8avv39
> Add "Quicker Quick Retry" hex edit for IIDX BISTROVER

- js/dllpatcher.js
Enables direct manipulation of hex values in the binary.   eg: changing hard-coded values or strings that may not necessarily be numerical.
> Support HexPatch

- ddra20+.html
Confirmed saving 20 songs in the same round on my local server.
> DDR A20P fake pfree score saving

- tricoro.html
Tried my best to port some of them from Spada; I personally tested timer freeze, CS song start delay, and premium timer freeze and can confirm they work
> Add missing tricoro patches

- resident.html
> Add Force Monitor Offset/Monitor Adjust Offset to LDJ-012

- drs.html
> feat: add patch for drs 2022-12-14

- resident.html
A necessary patch for asphyxia (skip region check), and a quality-of-life improvement for video upload speed.
My English is pretty bad, so if there's any grammar issue, please tell me and I'll change it.
> recording related patch for resident 010 dll

- ddra3.html
source: https://github.com/two-torial/sp2xpatcher/issues/22
> DDR A3: Add patch to enable Dan courses on regular cabinets
