mon/BemaniPatcher

sdvx4.html

This will only hide the text "PASELI: NOT AVAILABLE", but I think that that is enough. Feel free to improve.
Also I didn't test this with the enhanced continue (but did with the 2018-01-16), but it should work with no problems.

Add patches for hiding PASELI text (SDVX4)

---

ballerz.html

added hex edit to allow BGA preview on music select for all songs rather than being restricted to just the beginners folder.

updated with BGA Preview hex edit

---

ballerz.html
copula.html
pendual.html
sinobuz.html
spada.html
tricoro.html

Run monitor check for 300 frames instead of 1200, and show 6 digits in monitor check instead of 4

Add monitor check hex edits for all IIDX LDJ games (tricoro+)

---

ballerz.html

Here's something I randomly found while messing around with INFINITAS.
This hex edit skips the screen in-between selecting a chart and the fade-in, loading directly into the chart instead, saving you a whole 2~ seconds! _(might be more in some games)_
https://streamable.com/gsy68
It should work on any LDJ game but this patch is just for the latest IIDX 25 library.

Add hex edit to skip the decide screen.

---

ballerz.html
beatstream1.html
beatstream2.html
copula.html
gfdmv5.html
gfdmv6.html
gfdmv7.html
index.html
jubeatqubell.html
museca1.html
pendual.html
sinobuz.html

Sinobuz->SINOBUZ, Jubeat->jubeat etc
Removed numbers from games that didn't have them (museca, BST)
Also fixed a mistake with the GFDM pages, they all had the V5 title
BST AnimTribe has a line break on the index page so the name doesn't wrap weirdly (or whatever the word is)
without break: ![image](https://user-images.githubusercontent.com/23622616/58447790-994e2180-80d3-11e9-812f-430a1c2c783d.png)
with break: ![image](https://user-images.githubusercontent.com/23622616/58447811-abc85b00-80d3-11e9-9aa4-9a9c13a2aba5.png)

Adjust name capitalization/formatting

---

ddra.html

Add hex edits for DDR A to have an opaque background filter, enable cabinet lights for cabinet type 6, and unlock ORCA

---

museca2.html

I thought that maybe changing the last byte to a nop was better than actually having to shift the return to the left. Sorry for the double PR

Changed last byte to nop in museca2

---

rootage.html

This edit reduces the usual 1m5s wait time before CPUs join to 30 seconds.
Saves a bit of time when you're playing consecutive Arena matches with less than 4 people.

Add Shorter Arena timeout hex edit for 2019090200.

---

chuniamazon.html

Originally I was trying to patch function at 0x9C44A0 (set up timer seconds? ) and 0x9C41F0 (set up timer infinite display), but turns out it's just a display, the actual timer is still there. 
Then I found there's this "convient" multiply function, which takes second value and turns it into milliseconds? 
Patched it to always return 999000, and it actually works. 
Chose this value because: 
1. Chunithm timer can't hold larger than 1000 seconds.
2. Some timer (e.g. mode selection, map selection, ticket selection) adds 900 milliseconds to that value. When the timer value is over 1000 seconds, the game will actually play the "time up" sound once (because it reached 0).

Chuni: Set All Timers to 999

---

sdvx4.html
sdvx5.html

Hex edit for making the game think headphones are always plugged in.
Mainly designed for cabinets where plugging in headphones doesn't trigger the detection.

Add force enable headphones for SDVX IV & SDVX V.

---

heroicverse.html

When enabled, shows the "FA: -/SL: -" text below the judge table by default, rather than requiring VEFX to be held.
Ported from iidxhax, so thanks to Nagato for the original work.

Port fast/slow total opposite toggle from iidxhax.

---

js/dllpatcher.js
nostalgiaop2.html

This PR adds new patches for Op.2 that hide some of the text from the UI. It also includes an update to dllpatcher.js to allow an array of date codes to be used to describe an instance of `Patcher`. This provides the ability to visibly show support for multiple date codes that share the exact same patches. Otherwise, if you duplicate an instance of `Patcher` with the same patches, two patching windows get created because both will match the provided DLL file. If you do not think that supporting arrays is the correct way to go about this, then another alternative is to simply break out of the patch matching loop as soon as it has found a match, rather than continuing through the rest of the list.

feat(op2): Add new UI text patches

---

chuniamazon.html

This is a weird patch
I actually tried 255 (0xFF), and the credit counter rolled back to 0 without stopping, which is somehow extremely funny to me

Chunithm Amazon: Increase max credits to 254

---

chuniamazon.html

Found a interesting one when digging through chuni 1.00
there's a `dummy Bd15093` setting in `project.conf`, and turns out this setting exists all the way to star (1.20), until it's hardcoded in star plus (1.25)

Chunithm Amazon: Dummy LED

---

css/style.css
js/dllpatcher.js

Shows patches matched for full matches to help identify which version was uploaded (with accompanying green style).
Also, fixes force load text and buttons not hiding/clearing when uploading a matching file after a non-matching file without reloading the page.
Example from live version (fixed in this commit):

Show successful match, fix text/button reset

---

sdvx6.html

This patch allows cards that do not have E004 card IDs (such as mifare cards) to work

Add patch to allow non E004 cards to work

---

heroicverse.html

The patch removes volume limiter that gets applied when the game starts. LDJ will be slightly louder, TDJ will be significantly louder. As a small side effect the volume settings in TDJ test menu will be ignored.

Add volume fix for Heroic Verse TDJ

---

bistrover.html

hopefully I actually formatted it decently [and didn't typo] this time?
Currently the hide bottom text patch is now split between two patches to allow the choice of enabling LED ticker display without having freeplay on, since freeplay locks out the 4-song selection for BPL BATTLE.

BISTROVER: more patches for 0915

---

bistrover.html

Updating some English text, no patch changes in this PR.
1. Add a warning about SSE fix, since it can cause a crash that is difficult to troubleshoot.
2. Remove "Experimental" tag from the LDJ 120Hz patch since we've all been using it for a while now. This was causing newcomers to shy away from checking this option and causing more confusion than necessary.
3. Add a bit more text to explain what the shared mode audio patch does.

Update Bistrover tooltip and patch names

---

ddrx.html

The datecodes overlap, it's not a typo.

Add more DDR X

---

resident.html

Allows 'locked' songs (mostly licenses) to be recorded using the in-game subscreen thing
Alternative method to editing the flags in `video_music_list.xml`

Add "Disable Recording Lock" hex edit for IIDX RESIDENT

---

bistrover.html
casthour.html
resident.html

Fix for https://github.com/mon/BemaniPatcher/pull/342#issuecomment-1984898583, only alters the check _after_ recording is known to be supported and the player has accepted the T&Cs
Users of the previous edit will need to either revert the changes manually or re-apply from a clean DLL
Would definitely appreciate if you could test this new version out, @drmext

Fix recording lock crash on networks without Videos support

---

chusansun.html
chusansunplus.html

The first commit contains the actual changes, while the second commit is just formatting.
The patches added are:
- Allow 127.0.0.1/localhost as the network server
- Free play (infinite credits)
These patches were a pretty straightforward port from CHUNITHM pre-PARADISE, when amdaemon was built in to the game.

[chunithm] Add amdaemon patches for free play/local server usage

---

js/dllpatcher.js

Was originally going to make an issue for this but I ended up fixing it in the process. Original text detailing the bug below:
---
I think I've run into a bug with the output file when using dynamic patches. Here's one I wrote for the [INFINITAS launcher](https://d1rc4pwxnc0pe0.cloudfront.net/v3/resource/distribution/jp/2024031300/launcher/modules/bm2dx_launcher.exe):
```javascript
{
type: 'dynamic',
name: 'Bypass Game File Validation',
tooltip: 'Ignore expected SHA-256 from server, allowing the game to launch with a modified executable',
patches: [
{
off: [0x74, 'XX', 0xB9, 'XX', 'XX', 'XX', 'XX', 0xE8, 'XX', 'XX', 'XX', 'XX', 0x48, 0x8B, 0x7D],
on: [0xEB, 'XX', 0xB9, 'XX', 'XX', 'XX', 'XX', 0xE8, 'XX', 'XX', 'XX', 'XX', 0x48, 0x8B, 0x7D],
},
],
},
```
I'm only replacing the first byte, …

Fix copying original bytes in dynamic patches

---

gitadorafuzzup.html

Add big warnings to warn about scores not saving if PFree patches are not used properly.

GITADORA FUZZ-UP: Add warning about scores not saving

---

chusansunplus.html

This patch effectively removes R10.
The in-game rating in Chunithm is calculated roughly as follows (in pseudocode):
```
let r = 0
for s in best_scores.take(30):
r += s
for s in recent_30_scores.sort().take(10):
r += s
r /= 40
```
The general consensus is that taking recent scores into account defeats the purpose of the overall rating as a skill/progress tracker; they can deflate it from 16.x to 14.x when you're all-playing easier charts, or they can artificially inflate it when you spam your best chart a dozen times. Some people choose to hide the in-game rating specifically for this reason.
`0x6FF272` is the number of recent scores taken (10->0)
`0x6FF285` is the divisor (40->30)
The resulting value matches with a third-party score tracker that specifically only uses Best30.
* "... or …

Chusan: add a patch that removes recent scores from rating calculation

---

iidx30resident.html

Add the missing shared WASAPI patch for 010.
Port over "unscramble PIN pad" from CastHour. Only did 010 for now since that's the TDJ DLL, but could be ported to others if needed.

IIDX30-010: Add Unscramble PIN pad, shared WASAPI patches

---

iidx30resident.html

Ports over a missing patch from 003 to fix Omnimix charts not appearing in the folder
| Before  | After |
| -------- | ----- |
| ![20240925_1](https://github.com/user-attachments/assets/6fbc4c7d-31eb-40aa-948e-63cd896c3e16) | ![20240925_0](https://github.com/user-attachments/assets/95e90128-4966-4e0c-bf9a-3391fa7ad617) |

Fix missing LEGGENDARIA folder charts on non-003 RESIDENT

---

iidx31epolis.html

Maybe someone can figure out how to increase recording bitrate too

IIDX 31: 120fps recording output and subscreen timer freeze

---

iidx31epolis.html

Thanks to aixxe and Radioo https://github.com/mon/BemaniPatcher/pull/373

IIDX 31: Increase recording output quality
